<?php

namespace admin\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\rest\Controller;
use yii\web\Response;

/**
 * 公共 Ajax 接口
 */
class AjaxController extends Controller
{

    public $enableCsrfValidation = false;

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        Yii::$app->response->format = Response::FORMAT_JSON;
    }

    /**
     * 重定义 actions，去除默认的 curd 接口
     *
     * @return array
     */
    public function actions()
    {
        return [
            'options' => [
                'class' => 'yii\rest\OptionsAction',
            ],
        ];
    }

    /**
     * 级联下拉表单
     *
     * @param $model
     * @param $input
     * @param $exclude
     *
     * @return array
     */
    public function actionSelect($model, $input, $exclude)
    {
        $select = '';
        $parent_id = (int) Yii::$app->request->post('parent_id');

        if ($parent_id) {
            $data = $model::getSelectData($parent_id, $exclude);
            if ($data) {
                $select = Html::dropDownList($input, '', $data, [
                    'class' => 'form-control form-control-inline selectpicker',
                    'ajax-select' => Url::to([
                        'ajax/select',
                        'model' => $model,
                        'input' => $input,
                        'exclude' => $exclude,
                    ]),
                ]);
            }
        }

        return ['html' => $select];
    }

    /**
     * @param $model
     * @param $field
     *
     * @return array
     */
    public function actionOptions($model, $field)
    {
        $value = Yii::$app->request->post('value');

        return ['html' => $model::getOptions([$field => $value])];
    }

    /**
     * @param string|array $message
     * @param array $data
     *
     * @return array
     */
    public function success($message, array $data = []): array
    {
        return $this->output($message, 0, $data);
    }

    /**
     * @param string|array $message
     * @param int $code
     * @param array $data
     *
     * @return array
     */
    public function output($message, $code, array $data = []): array
    {
        if (is_array($message)) {
            return $message;
        }

        $data['code'] = $code;
        $data['message'] = $message;

        return $data;
    }

    /**
     * @param string|array $message
     * @param int $code
     * @param array $data
     *
     * @return array
     */
    public function error($message, int $code = 1, array $data = []): array
    {
        return $this->output($message, $code, $data);
    }
}
